[server]
host = "127.0.0.1"
port = 1062
workers = 2

[[traps]]
oid = ".1.3.4.5.6.7"
format = "$a a trap man: $*"
notify = ["datadog", "slack"]
generic = coldStart
exec = [ "do_things $*", "do_more_things $1 $3"]

[[traps]]
oid = ".1.3.6.*"
format = "$a wild card trap"
notify = ["datadog", "slack"]
when = "$1 == 1.2.3.4"
